language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy tailhn/reverseproxy:v1a
  - docker tag udagram-api-user tailhn/udagram-api-user:v1a
  - docker tag udagram-api-feed tailhn/udagram-api-feed:v1a
  - docker tag udagram-frontend:local tailhn/udagram-frontend:v1a

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
  - docker push tailhn/reverseproxy:v1a
  - docker push tailhn/udagram-api-user:v1a
  - docker push tailhn/udagram-api-feed:v1a
  - docker push tailhn/udagram-frontend:v1a
